config/routes.rb
Nearby::Application.routes.draw do
  resources :topics

  resources :users do
    resources :wants
    member do
      post 'send_invite'
    end
    collection do
      get 'new_csv'
      post 'import_csv'
      post 'invite'
    end
  end

  resources :events do
    member do
      post 'plan'
      post 'forget'
    end
    collection do
      post 'want'
      post 'want_topic'
      post 'update_exclude'
    end
  end

  get 'admin_index' => 'events#admin_index', :as => :admin_index
  post 'login' => 'sessions#create', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout
  get 'about' => 'events#about', :as => :about

 root :to => 'events#index'

end

app/models/user.rb
class User < ActiveRecord::Base
#  attr_accessible :name, :email, :affiliation, :furigana, :category, :sex, :password, :password_confirmation, :insecure_password
  has_secure_password
  validates :password, presence: true, on: :create
  
  scope :excluded, -> { where exclude: true }
  scope :included, -> { where exclude: false }
  scope :with_wants, -> { joins(:wants).uniq }

  has_many :wants, :dependent => :destroy
  has_many :wanted, as: :wantable

  has_many :seatings
  has_many :tables, :through => :seatings
  
  has_many :topics

#   def self.with_wants
#     all.reject{|u| u.wants.empty? }
#   end

  def self.for_select
    all.map{|u| [u.name, u.id]  }.group_by { |u| u[0].length }
  end
  
  def self.grouped_options_by_affiliation
    g = all.group_by{|u| u.affiliation }
    g.each{|k, us| g[k] = us.map{|u| [u.name, u.id, 'data-category' => u.category ] } }
  end
  
  def self.grouped_options_by_furigana
    g = all.group_by{|u| u.furigana[0] }
    g.each{|k, us| g[k] = us.map{|u| [u.name, u.id]} }
  end
 
  def name_with_affiliation
    "#{name} (#{affiliation})"
  end
  
  def topics
    wants.select{|w| w.wantable_type == 'Topic' }.map{|w| w.wantable }
  end
  
  def popularity
    Want.where(wantable_type: 'User', wantable_id: self.id).count
  end
  
  # 重いので注意
  def satisfied?
    wants.any?{|w| w.satisfied? }
  end
  
  def impossible?
    wants.all?{|w| w.impossible? }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  http_basic_authenticate_with :name => 'tnishida', :password => '3594t'

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
#    @user = User.new(params[:user])
    @user = User.new(user_params)
    @user.insecure_password = params[:user][:password] # VERY BAD! (just for now)
    if @user.save
      redirect_to root_url, notice: 'Signed up!'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # @user.update(params[:user])
    @user.update(user_params)
    redirect_to @user
  end

  def new_csv
    @users = User.all
  end

  def import_csv
    require 'csv'
    require 'kconv'

    s = params[:csv].read
#    s.force_encoding("Shift_JIS")

    CSV.parse(s, headers: true) do |row|
      @user = User.new(
        name: row['name'],
        email: row['email'],
        password: row['password'],
        password_confirmation: row['password'],
        insecure_password: row['password'], # VERY BAD! (just for now...)
        furigana: row['furigana'],
        affiliation: row['affiliation'],
        category: row['category'],
        sex: row['sex'].to_i
      )
      @user.save
    end

    redirect_to action: 'index'
  end

  def invite
    @users = User.all
    @users.each{|user| AnnounceMailer.invite(user).deliver }
    render :index
  end

  def send_invite
    @users = User.all
    @user = User.find(params[:id])
    AnnounceMailer.invite(@user).deliver
    render :index
  end

  protected

  def user_params
    params.require(:user).permit(:name, :email, :affiliation, :sex, :category, :password, :password_confirmation, :password_digest, :exclude)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each {|message| %>
          <li><%= message %></li>
        <% } %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, required: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email %>
  <%= f.email_field :email, required: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :affiliation %>
  <%= f.text_field :affiliation, required: true, class: 'form-control' %>
</div>

<div class="form-group">
  <label class="radio-inline"><%= f.radio_button :sex, 0 %> Male</label>
  <label class="radio-inline"><%= f.radio_button :sex, 1 %> Female</label>
</div>

<div class="form-group">
  <%= f.label :category %>
  <%= f.select :category, participation_types, { }, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, required: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, required: true, class: 'form-control' %>
</div>

<div class="checkbox">
  <label><%= f.check_box :exclude %> 席決め対象外にする</label>
</div>
<%= f.submit '登録', class: 'btn btn-default' %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザデータの編集</h1>
<%= render partial: 'form' %>

app/views/users/index.html.erb
<div>
  <%= button_to '招待メール送信', invite_users_path, class: 'btn btn-default' %>
</div>

<h1>ユーザ一覧</h1>

  <ul>
    <% @users.each{|u|  -%>
      <li>
        <%= u.wants.count %>: <%= link_to u.name, user_path(u)  %> (<%= u.furigana %>) <%= u.email %>
        <%= link_to '編集する', edit_user_path(u) %>
        <%= button_to '招待メールを送る', send_invite_user_path(u) %>
      </li>
    <% } -%>
  </ul>

app/views/users/new.html.erb
<h1>ユーザ登録</h1>
<%= render partial: 'form' %>

app/views/users/new_csv.html.erb
<h1>ユーザ一括登録</h1>

<%= form_tag import_csv_users_path, multipart: true do -%>
<div class="form-group">
  <label>CSVファイル</label><%= file_field_tag 'csv', accept: 'csv' %>
</div>
  <%= submit_tag '送信', class: 'btn btn-default' %>
<% end -%>

<% @users.each{|user| %>
  <%=  user.name %>
<% } %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p>所属: <%= @user.affiliation %>, ふりがな: <%= @user.furigana  %></p>
<p><%= link_to 'トップページに戻る', :root %></p>