config/routes.rb
Nearby::Application.routes.draw do
  resources :topics

  resources :users do
    resources :wants
    member do
      post 'send_invite'
    end
    collection do
      get 'new_csv'
      post 'import_csv'
      post 'invite'
    end
  end

  resources :events do
    member do
      post 'plan'
      post 'forget'
    end
    collection do
      post 'want'
      post 'want_topic'
      post 'update_exclude'
    end
  end

  get 'admin_index' => 'events#admin_index', :as => :admin_index
  post 'login' => 'sessions#create', :as => :login
  post 'logout' => 'sessions#destroy', :as => :logout
  get 'about' => 'events#about', :as => :about

 root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validate :has_enough_seats, :rows_should_be_even

  has_many :tables, :dependent => :delete_all
  has_many :seatings, :through => :tables#,  :dependent => :delete_all
  has_many :users, :through => :seatings

  def planned?
    !tables.empty?
  end

  # 重いので注意
  def partition(wants)
    wants.partition{|w|
      case w.wantable_type
      when 'User'
#        s1 = seatings.find_by_user_id(w.who.id)
#        s2 = seatings.find_by_user_id(w.wantable.id)
#        s1 && s2 && s1.table == s2.table
        tables.any?{|table| (table.users & [w.who, w.wantable]).size == 2 }
      when 'Topic'
        tables.any?{|table| table.popular_topics.include?(w.wantable) }
      end
    }
  end

  def forget_seating
    tables.clear
#    seatings.clear
  end

  # このイベントで自由席になったユーザのリストを返す
  def excluded_users
    User.all - users # TODO: better written by join?
  end

  def plan_seating(priorities)
    SEAT_PLANNERS[style].new(self, 1).plan_seating(priorities) unless planned?

    # unless planned?
    #   # case style
    #   #   when 'tables'
    #   #     plan_seating_tables(priorities)
    #   #   when 'rows'
    #   #     plan_seating_rows(priorities)
    #   # end
    # end
  end

  protected

  SEAT_PLANNERS = { 'tables' => TablesSeatPlanner, 'rows' => RowsSeatPlanner, 'zashiki' => ZashikiSeatPlanner }

  #########################################################
  # Seat planning
  #########################################################

  # def plan_seating_tables(priorities)
  #   plans = Array.new
  #   1.times{ plans << plan_seating_impl(initial_seating_tables, priorities) }
  #   best, bestscore = plans.max_by { |plan, score|  score }
  #   best = best.group_by{|user, table| table }.values.sort_by{|table| table.size }
  #   save_seatings(best)
  # end

  # def plan_seating_rows(priorities)
  #   plans = Array.new
  #   1.times{ plans << plan_seating_impl(initial_seating_rows, priorities) }
  #   best, bestscore = plans.max_by { |plan, score|  score }
  #
  #   # 2. 4人テーブルを、なるべくテーブルを越えての会話が成り立たなくなるように並べる
  #   best = best.group_by{|user, table| table }.values
  #
  #   a = Array.new
  #   min = best.min_by{|us| us.length }
  #   best.delete(min)
  #   a << min
  #   until best.empty?
  #     min = best.min_by {|us| tables_matching(min, us, priorities) }
  #     best.delete(min)
  #     a << min
  #   end
  #
  #   # 4. 席決め結果を記録する
  #   save_seatings(a.reverse)
  # end

#   # example setting: 4users x 2 + 2users x 4 = 16
#   # 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 (user index)
#   # 0 1 0 1 0 1 0 1 2 3  4   5    2   3   4   5 (initial table number)
#   def initial_seating_tables
#     sn1 = size1 * number1
#     h = Hash.new
#     users = User.included.shuffle
# #    users = User.included.sort_by{|u| u.popularity } # 希望されていない順に並べる（人気者が size2 の方に入るように　size2 > size1 と仮定）
#     users.take(sn1).each_with_index{|u, i| h[u.id] = i % number1 }
#     users.drop(sn1).each_with_index{|u, i| h[u.id] = i % number2 + number1 }
#     h
#   end

  # def initial_seating_rows
  #   h = Hash.new
  #   User.included.shuffle.each_with_index{|u, i| h[u.id] = i / 4 } # 1. ４人テーブルだと思って分割する
  #   h
  # end

  # def plan_seating_impl(h, priorities)
  #   best = h
  #   p_user, p_topic, p_done = priorities
  #   pairs = p_user.merge(p_topic){|_,v1,v2| [v1, v2].max }.sort_by{|pair, v| -v }.map{|pair, v| pair }
  #   unsatisfied = pairs.reject{|u1,u2| sametable?(h, u1, u2) }
  #
  #   until unsatisfied.empty?
  #     best, max, improved = h, total_priority(h, priorities), false
  #
  #     unsatisfied.shuffle.each{|u1, u2|
  #       next if sametable?(h, u1, u2)
  #       prevh = h.clone
  #
  #       users1 = users_together(h, u1)
  #       users2 = users_together(h, u2)
  #
  #       next if users1.empty? && users2.empty?
  #
  #       if wantedscore(u1, users1, priorities) > wantedscore(u2, users2, priorities) # 元の部屋にそのままいる方が良い方を残す
  #         unless users1.empty?
  #           temp_users = users1 + [u2]
  #           swap(h, u2, users1.max{|u| table_priority(temp_users - [u], priorities) }) #u2 が users1 の誰か (u1以外) と入れ替わる
  #         end
  #       else
  #         unless users2.empty?
  #           temp_users = users2 + [u1]
  #           swap(h, u1, users2.max{|u| table_priority(temp_users - [u], priorities) }) # u1 が users2 の誰か (u2以外) と入れ替わる
  #         end
  #       end
  #
  #       # 入れ替え結果を評価する
  #       score = total_priority(h, priorities)
  #       if score > max
  #         best, max, improved = h.clone, score, true
  #       else
  #         h = prevh
  #       end
  #     }
  #
  #     unsatisfied = pairs.reject{|u1, u2| sametable?(best, u1, u2) }
  #     if improved
  #       h = best
  #     else
  #       break # 改善が見られなかったら、全ての希望を満たしていなくても探索終了
  #     end
  #   end
  #
  #   return best,  total_priority(best, priorities)
  # end

  # def save_seatings(groups)
  #   groups.each{|us|
  #     tables.create(:user_ids => us.map{|u, t| u} )
  #   }
  # end

  # #########################################################
  # # Seat planning helper methods
  # #########################################################
  #
  # def sametable?(h, user1, user2)
  #   h[user1] == h[user2]
  # end
  #
  # # user と同じテーブルにいるユーザ全員 (user を除く)
  # def users_together(h, user)
  #   h.select{|u, table| table == h[user] && user != u }.map{|u, _| u }
  # end
  #
  # # u1 と u2 が同じテーブルに着いた場合の評価値
  # def pair_priority(u1, u2, priorities)
  #   pair = [u1, u2].sort
  #   priorities.map{|p| p[pair] }.reduce(:+)
  # end
  #
  # # あるテーブルの合計評価値 (users: 同じテーブルに着いたユーザ)
  # def table_priority(users, priorities)
  #   return 0 unless users.length > 1
  #   p_user, p_topic, p_done = priorities
  #   too_satisfied = Hash.new(0)
  #   users.permutation(2).group_by{|u1, u2| u1 }.each{|u, pairs|
  #     too_satisfied[u] = pairs.count{|pair| p_user.include?(pair.sort) } > 4 # 人希望が叶いすぎているのはダメ！
  #   }
  #   users.combination(2).map{|u1, u2|
  #     key = [u1, u2].sort
  #     p_topic[key] + p_done[key] + ((too_satisfied[u1] || too_satisfied[u2]) ? 0 : p_user[key])
  #   }.reduce(:+)
  # end
  #
  # # 決めた席全体の合計評価値
  # def total_priority(h, priorities)
  #   h.group_by{|u, t| t}.map{|table, users| table_priority(users.map{|u,t| u}, priorities) }.reduce(:+)
  # end
  #
  # # user が users の中にいることの評価値
  # def wantedscore(user, users, priorities)
  #   users.length > 0 ? users.map{|u| pair_priority(u, user, priorities) }.reduce(:+) : 0
  # end
  #
  # # used in plan_seating_rows
  # def tables_matching(users1, users2, priorities)
  #   users1.product(users2).map{|u1,u2| pair_priority(u1,u2, priorities) }.reduce(:+)
  # end
  #
  # def swap(h, u1, u2)
  #   temp = h[u1]
  #   h[u1] = h[u2]
  #   h[u2] = temp
  # end

  #########################################################
  # Validation methods
  #########################################################

  def has_enough_seats
    if size1 * number1 + size2 * number2 < User.count
      errors.add(:size1, 'not enough seats compared to participants')
      errors.add(:size2, 'not enough seats compared to participants')
      errors.add(:number1, 'not enough seats compared to participants')
      errors.add(:number2, 'not enough seats compared to participants')
    end
  end

  def rows_should_be_even
    if style == 'rows'
      errors.add(:size1, 'row size has to be even') if size1 % 2 != 0
      errors.add(:number1, 'row number has to be even') if number1 % 2 != 0
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
#  http_basic_authenticate_with :name => "wiss2012", :password => "aomori338", :only => [:index]
  http_basic_authenticate_with :name => 'tnishida', :password => '3594t', :only => [:new, :create, :plan, :forget, :admin_index]

  before_action :current_user, only: [:want, :want_topic]

  def index
    @events = Event.all
#    @users = User.all
    @topics = Topic.all
    @want = Want.new
    @grouped_users = User.grouped_options_by_affiliation
    @affiliations = @grouped_users.keys.sort
  end

  def admin_index
    @events = Event.all
    @wants = Want.all
    @topics = Topic.all
  end

  def show
    @event = Event.find(params[:id])
#    @excluded_users = @event.excluded_users
#    @wants = Want.for_user
#    @satisfied, @unsatisfied = @event.partition(@wants) if @event.planned?
  end

  def new
    @event = Event.new(style: 'tables', size1: 4, number1: User.count / 4, size2: 0, number2: 0)
  end

  def create
    @event = Event.new(params.require(:event).permit(:description, :style, :size1, :number1, :size2, :number2))
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.forget_seating
    @event.destroy
    redirect_to :admin_index
  end

  def plan
    @event = Event.find(params[:id])
    @event.plan_seating(Want.priorities)
    redirect_to :admin_index
  end

  def forget
    @event = Event.find(params[:id])
    @event.forget_seating
    redirect_to :admin_index
  end

  def want
    @want = current_user.wants.build(params.require(:want).permit(:who_id, :wantable_id))
    @want.wantable_type = 'User'

    if @want.save
    else
      flash['alert'] = '無効な希望です'
      flash.keep
    end
      redirect_to root_url
  end

  def want_topic
    @want = current_user.wants.build(params.require(:want).permit(:wantable_id))
    @want.who = current_user
    @want.wantable_type = 'Topic'

    if @want.save
    else
    end

    redirect_to root_url
  end

  def update_exclude
    current_user.exclude = params[:exclude] ? true : false
    current_user.save
    puts current_user.exclude
    redirect_to root_url
  end

end

app/helpers/events_helper.rb
# -*- coding: utf-8 -*-

module EventsHelper
  
  def event_details(e)
    h1 = { tables: 'テーブル席', rows: '座敷'}
    h2 = { tables: '個', rows: '列'}
    s = "#{h1[e.style]} ("
    s << "#{e.size1}人 × #{e.number1}#{h2[e.style]}" if e.number1 > 0
    s << " + #{e.size2}人 × #{e.number2}#{h2[e.style]}" if e.number2 > 0
    s << "), 席決め人数: #{e.users.count}人"
  end

  def human_readable_want(w)
    case w.wantable_type
    when 'User'
      "#{w.who.name} さんが #{w.wantable.name} さんが近くの席になれたらいいな"
    when 'Topic'
      "#{w.wantable.description if w.wantable} の話がしたい"
    end
  rescue
    "error: #{w.who} / #{w.wantable}"
  end
        
  def plan_button_for(event)
    if event.planned?
      button_to '決めた席をなかったことにする', forget_event_path(event)
    else
      button_to '席を決める', plan_event_path(event)
    end
  end
  
  def zashiki_style_name(i)
    i / 2 % 2 == 0 ? 'even-col' : 'odd-col'
  end

  # 4人分割の配列から座敷用の列を生成する
  def tables_to_rows(event)
    # 1. 4人未満のテーブルを4人に揃える
    a = event.tables.collect{|table| fill_to(table.users, 4) }

    # 2. 座敷の席数に配列の長さを揃える
    a = fill_to(a, event.size1 * event.number1 / 4)
    
    # 3. 転置の下準備をする
    b = Array.new
    a.each_slice(event.size1 / 2){|slice| b << slice }

    # 4. 転置して、各テーブルから2人を１行に、残りの2人を次の行に入れる
    c = Array.new
    b.transpose.each{|row|
      c << row.collect{|users| users ? users[0,2] : [nil] * 2}.flatten
      c << row.collect{|users| users ? users[2,2] : [nil] * 2}.flatten
    }
    c
  end
  
  # 配列 a の長さを n に揃える（不足分は nil で埋める）
  def fill_to(a, n)
    a.length < n ? a + [nil] * (n - a.length) : a
  end

  def status_mark(w)
    if w.satisfied?
      '○'
    else
      w.impossible? ? '▼' : '×'
    end
  end

  # 2人分割の配列から座敷用の列を生成する
  def tables_to_zashiki(event)
    # 1. 1人テーブルを2人にそろえる
    a = event.tables.collect{|table| fill_to(table.users, 2) }

    # 2. 座敷の席数に配列の長さを揃える
    a = fill_to(a, event.size1 * event.number1 / 2)

    # 3. 各ペアから1人を1行に、もう1人を次の行に入れる
    b = Array.new
    a.each_slice(event.number1).with_index{|slice, i|
      if i < event.size1 / 2 then
        b << slice.collect{|pair| pair ? pair[0] : nil }
        b << slice.collect{|pair| pair ? pair[1] : nil }
      else
        b << slice.flatten
      end
    }

    b
  end
end

app/views/events/_rows.html.erb
<table class="rows">
    <col />
  <% event.number1.times{|i| -%>
    <col class="<%= zashiki_style_name(i)  %>" />
  <% } -%>
  <tr>
    <th></th>
  <% ('A'..'Z').first(event.number1).each{|a| -%>
    <th><%= a  %></th>
  <% } -%>
  </tr>
  <% tables_to_rows(event).each_with_index{|users, i| -%>
    <tr>
      <th><%=  i + 1 %></th>
      <% users.each{|u| %>
      <td><div class="keep_short"><%= u ? u.name : '[空席]' %></div></td>
      <% } %>
    </tr>
  <% } -%>
  </table>

app/views/events/_tables.html.erb
<div class="rows">
  <% event.tables.each_with_index{|table, i| %>
    <div class="col-lg-3 col-sm-4 col-xs-6">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= i + 1 %>番テーブル<br>
          <small>
            <% table.popular_topics.each{|t| %>
              <%= content_tag 'span', t.description, class: 'label label-default' %>
              <% } %>
            </small>
          </div>
          <div class="panel-body">
            <ol>
              <% table.users.each_with_index{|u, _| -%>
                <li><%= u.name %></li>
              <% } -%>
            </ol>
          </div>
        </div>
      </div>
    <% } %>
    </div>

app/views/events/_zashiki.html.erb
<table class="rows">
  <col />
  <% event.number1.times{|i| -%>
      <col class="<%= zashiki_style_name(i)  %>" />
  <% } -%>

  <thead>
  <tr>
    <th />
    <% ('A'..'Z').first(event.number1).each{|a| -%>
        <th><%= a  %></th>
    <% } -%>
  </tr>
  </thead>

  <tbody>
  <% tables_to_zashiki(event).each_with_index { |users, i| -%>
      <tr>
        <th><%= i + 1 %></th>
        <% users.each{|u| -%>
            <td><div class="keep_short"><%= u ? u.name : '[空席]' %></div></td>
        <% } -%>
      </tr>
  <% } -%>
  </tbody>
</table>

app/views/events/admin_index.html.erb
<h1>管理者メニュー</h1>

<ul class="list-inline">
  <li><%= link_to 'イベント登録', new_event_path %></li>
  <li><%= link_to 'ユーザ登録', new_user_path %></li>
  <li><%= link_to 'ユーザ一括登録(CSV)', new_csv_users_path %></li>
  <li><%= link_to 'ユーザ一覧', users_path %></li>
</ul>

<h2>希望充足度</h2>
<ul>
  <li>席決め対象人数: <%= User.included.count %> / <%= User.count %></li>
  <li>
    希望のかなった人数: <%= User.with_wants.select{|u| u.satisfied? }.size %> / <%= User.with_wants.size  %>
    (うち <%= User.with_wants.select{|u| u.impossible?}.size %> 人は満たせる希望がない)
  </li>
  <li>自分で自分の席を決めたいを選んだ人数: <%= User.excluded.count %></li>
  <li>全希望:<%= @wants.count{|w| w.satisfied? }%> / <%= @wants.length %> (うち<%= @wants.count{|w| w.impossible?} %>満たせない)</li>
  <li>人希望: <%= Want.for_user.select{|w| w.satisfied? }.size %> / <%= Want.for_user.count %> (うち<%= Want.for_user.select{|w| w.impossible? }.size %>満たせない)</li>
  <li>話題希望: <%= Want.for_topic.select{|w| w.satisfied? }.size %> / <%= Want.for_topic.count %> (うち<%= Want.for_topic.select{|w| w.impossible? }.size %>満たせない)</li>
</ul>

<h2>イベント一覧</h2>
<table>
  <tr><th>イベント名</th><th>設定</th><th>叶えた人希望の数</th><th colspan="2">ボタン</th></tr>
<% @events.each do |event| -%>
  <% satisfied, unsatisfied = event.partition(@wants) %>
  <tr>
    <td><%=  link_to event.description, event_path(event) %></td>
    <td><%= event_details(event) %></td>
    <td><%= satisfied.select{|w| w.wantable_type == 'User' }.size %> 個</td>
    <td><%= plan_button_for(event) %></td>
    <td><%= button_to '削除', event_path(event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end -%>
</table>

<h2>トピック一覧</h2>
<ul>
  <% @topics.sort_by{|topic| topic.wants.size }.each{|topic| -%>
  <li>(<%= topic.wants.size %>) <%= topic.description %></li>
  <% } -%>
</ul>

<h2>希望満足状況の詳細</h2>
<% User.with_wants.each{|u| %>
<h3><%= u.name %><%= '○' if u.satisfied? %><%= ' ※自由席希望' if u.exclude %></h3>
<ul>
  <% u.wants.each{|w| -%>
  <li><%= status_mark(w) %><%= human_readable_want(w) %></li>
  <% } -%>
</ul>
<% } %>

app/views/events/index.html.erb
<%= content_tag 'p', flash['alert'], class: 'alert alert-warning' if flash['alert'] %>

<h2>システム趣旨説明</h2>
<p>
  「○○さんと話したい」などの希望をみなさんに入力していただき、それをもとに夕食の座席を決めるシステムです。
  WISS2012, 2013, 2014 に運用されたシステムが5年ぶりの復活です。
  <%= link_to '詳細＆FAQ', :about  %>
</p>

<div class="row three">
<div class="col-sm-4">
<h2>利用手順</h2>
<ol>
  <%= content_tag 'li', 'ログインする', class: current_user ? 'text-muted' : 'alert-success' %>
  <%= content_tag 'li', '希望を入力する', class: current_user ? 'alert-success' : '' %>
  <li>夕食の際に、席次表を確認して着席する</li>
</ol>
</div>

<div class="col-sm-4">
<h2>席次表</h2>
<ul class="list-inline">
  <% @events.each{|e| -%>
      <li><%= link_to e.description, event_path(e)  %></li>
  <% } -%>
</ul>
</div>

<div class="col-sm-4">
<h2>みんなの希望</h2>
<span class="xx-large"><%= User.all.count %></span> 人中 <span class="xx-large"><%= User.with_wants.count %></span> 人の参加者が合計で
<span class="xx-large"><%= Want.all.count %></span> 個の希望を登録しています
</div>

</div>


<% if current_user %>
    <h2>あなたが登録した希望</h2>
    <% if current_user.exclude %>
    <p class="text-danger">
      ※「席を決められたくない」が設定されています。希望を登録しても席決めの対象外になります。（ほかの人に関する希望は席決めで考慮されます。）<br/>
      席決め対象になりたい場合は、下の方にあるチェックをオフにして更新ボタンを押してください。
    </p>
    <% end %>
    <table id="wishlist">
    <% current_user.wants.each{|want| -%>
      <tr>
        <td><%= human_readable_want(want) %></td>
        <td><%= button_to 'やっぱりやめる', user_want_path(current_user, want), method: :delete, data: { confirm: '本当にやめますか？' } %></td>
      </tr>
    <% } -%>
    </table>

    <h2>希望を登録する</h2>
  <p>
    夕食のときに近くになりたい人がいる場合、引き合わせたい二人がいる場合は、すぐ下で登録できます。<br/>
    特定の誰かは思い当たらないけどこういう話をしたいという希望はその下で話題を希望できます。<br/>
  </p>

  <div class="well well-want">
    <div class="btn-group">
      <button class="btn btn-default btn-xs" data-toggle="modal" data-target="#narrowdown">絞り込む</button>
      <button class="btn btn-default btn-xs" id="cancel_narrowdown_button1">解除</button>
    </div>
    <!--☆:登壇 ○:デモ・ポスター □:PC委員-->
  <%= form_tag want_events_path, id: 'want_people' do -%>
    <%= select :want, :who_id, grouped_options_for_select(@grouped_users, current_user.id), {}, id: 'select_who', class: 'who' %> さんと
    <%= select :want, :wantable_id, grouped_options_for_select(@grouped_users, nil, prompt: '選択されていません'), {}, id: 'select_wantable', class: 'who' %>　さんが
    <%= submit_tag '近くの席になれたらいいな' %>
    <%#= collection_select :want, :who_id, @users, :id, :name, selected: current_user.id %>
    <%#*<button class="btn btn-default btn-xs">絞り込む&gt;</button>%>
    <%#= collection_select :want, :wantable_id, @users, :id, :name %>
    <p class="help-block">
      リストが長くて選びにくいので上の「絞り込み」も使ってみてください。
    </p>
  <% end -%>
  </div>

    <div id="narrowdown" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">絞り込みの設定</h4>
        </div>
        <div class="modal-body">
          <div class="form-group"><label>参加形態</label>
            <select multiple id="select_types" size="5" class="form-control"><%= options_for_select participation_types %></select>
          </div>
          <div class="form-group"><label>所属</label>
            <select multiple id="select_affiliations" size="8" class="form-control"><%= options_for_select @affiliations %></select>
          </div>
        </div>
        <div class="modal-footer">
          <button id="cancel_narrowdown_button2" class="btn btn-default cancel_narrow_down" data-dismiss="modal">絞り込みを解除する</button>
          <button id="narrowdown_button" class="btn btn-primary" data-dismiss="modal">絞り込む</button>
        </div>
      </div>
    </div>
  </div>

  <select id="select_clone" style="display: none"></select>

  <div class="well well-want">
  <%= form_tag want_topic_events_path do -%>
    <%= collection_select :want, :wantable_id, @topics, :id, :description %>
    の<%= submit_tag '話がしたい' %>
    <%= link_to '他の話題をリストに追加する', new_topic_url %>
  <% end -%>
    <p class="help-block">
      同じ話題を希望している人どうしは近くの席になりやすくなります。<br/>
      自分の研究テーマを <%= link_to '話題としてリストに追加', new_topic_url %> してみてもいいかも？<br/>
      話題を追加した後、話題を希望するのをお忘れなく。
    </p>
  </div>

  <div class="well well-exclude">
    <%=  form_tag update_exclude_events_path do -%>
      <%= check_box_tag :exclude, true, current_user.exclude %>
      <%= label_tag(:exclude, '席を決められたくない') %>
      <%= submit_tag '更新' %>
    <% end -%>
    <p class="help-block">
      席決めの対象外になります。<br/>対象外に設定した人数の分、席が残りますので、そのどれかに座ってください。<br/>
    </p>
  </div>


<% end -%>

<% unless current_user %>
    <h2>ログイン</h2>

    <%= form_tag login_path, id: 'login' do -%>
    <div class="form-group">
      <%= label_tag :email, 'メールアドレス' %>
      <%= email_field_tag :email, nil, placeholder: '案内メールが届いたメールアドレスを入力してください', class: 'form-control' %>
      <%#= select_tag :user_id, grouped_options_for_select(@grouped_users), prompt: "名前を選択してください", id: "select_user" %>
    </div>
    <div class="form-group">
      <%= label_tag :password, 'パスワード' %>
      <%= password_field_tag :password, nil, placeholder: '案内メールに記載のパスワードを入力してください', class: 'form-control' %>
    </div>
      <%= submit_tag 'ログイン', class: 'btn btn-default' %>
    <% end -%>
<% end -%>


<div class="footer">
<%= link_to '管理者用', admin_index_path %>
</div>

app/views/events/new.html.erb
<h1>イベント登録</h1>

<%= form_for @event do |f| -%>
<div class="form-group">
  <%= f.label :description, 'イベントの名称' %>
  <%= f.text_field :description, class: 'form-control' %>
</div>
<div class="form-group">
  <h2>座席レイアウトの設定</h2>
  <%= f.radio_button(:style, 'tables') %>テーブル席<br/>
  <%= f.radio_button(:style, 'rows') %>長いテーブル席<br/>
  <%= f.radio_button(:style, 'zashiki') %>お座敷
</div>
<div class="form-group">
  <h2>座席数の設定</h2>
  テーブル (or 列) 種類1: <%= f.text_field :size1, size: 3 %>人 &times; <%= f.text_field :number1, size: 3 %>個<br />
  テーブル (or 列) 種類2: <%= f.text_field :size2, size: 3 %>人 &times; <%= f.text_field :number2, size: 3 %>個<br />
  <strong>※合計 <%= User.count %> 人分の座席があるように設定してください</strong>
</div>
  <%= f.submit '登録', class: 'btn btn-default' %>
<% end -%>

app/views/events/show.html.erb
<h1><%= @event.description %>の席</h1>
<!--<p><%= event_details(@event) %></p>-->

<%#= @priorities.to_s %>

<%# if @event.planned? then -%>
<%#*<div>%>
<%#*<h2>Satisfied</h2>%>
<%#= @satisfied.map{|w| human_readable_want(w) }.join(" / ") %>

<%#*<h2>Unsatisfied</h2>%>
<%#= @unsatisfied.map{|w| human_readable_want(w) }.join(" / ") %>
<%#*</div>%>
<%# end %>

<% if @event.planned? -%>
  <%= render :partial => @event.style, :locals => { :event => @event } %>

  <% unless @event.users.exists?(exclude: true) %>
    <h2>席の決まっていない人</h2>
    <ul class="list-inline">
      <% @event.excluded_users.each do |u| -%>
        <li><%= u.name %></li>
      <% end -%>  
    </ul>
  <% end -%>

<% else -%>
  <p>決まった席はここで確認できますが、座席はまだ決まっていません。</p>
<% end -%>